<a href="https://colab.research.google.com/github/quadspark/basic-ml-course/blob/Week5/05_Naive_Bayes/Solution5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')
newsgroups_test = fetch_20newsgroups(subset='test')

In [141]:
len(newsgroups_train.data)

11314

In [ ]:
newsgroups_train.target, newsgroups_train.target_names

In [160]:
newsgroups_train.data[0]

"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [162]:
def remove_tokens(token_list, text):
    for token in token_list:
        text = text.replace(token, '')
    return text

In [180]:
from string import punctuation
preprocessed_text = [remove_tokens(punctuation, text) for text in newsgroups_train.data]
new_text = preprocessed_text
number_words = len(new_text)
print(number_words)

11314


In [155]:
from sklearn.feature_extraction.text import CountVectorizer
num_word = 30000
vectorizer = CountVectorizer(max_features=num_word)
train_data = vectorizer.fit_transform(preprocessed_text).toarray()
train_data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [148]:
import numpy as np
classes,class_freq = np.unique(newsgroups_train.target, return_counts=True)
prior_prob = class_freq//np.sum(class_freq)


In [ ]:
word_label_freq = classes/ np.sum(classes,axis = 0)
word_label_freq

In [ ]:
alpha = 0.01
cond_prob = np.array([(word_label_freq[i] + alpha)/(class_freq[i] + num_word * alpha) 
  for i in range(len(class_freq))]) 
cond_prob

In [83]:
def find_label(data):
  
    indices = np.where(data > 0)
    indices_0 = np.where(data==0)
  
    max_value = -1e18
    result_class = 0
    for i,class_val in enumerate(cond_prob):
      prod = np.log(prior_prob[i]) + np.sum(np.log(class_val[indices])) + np.sum(np.log(1 - class_val[indices_0]))
      if prod >= max_value:
        result_class = i
        mx_val = prod
    return result_class
  

In [157]:
preprocessed_test_text = [remove_tokens(punctuation, text) for text in newsgroups_test.data]
test_data = vectorizer.transform(preprocessed_test_text)

pred = [newsgroups_train.target]
from tqdm import tqdm
for text in tqdm(test_data):
 pred.append(find_label)

7532it [00:00, 24298.57it/s]


In [156]:
from sklearn import metrics
metrics.accuracy_score(pred, newsgroups_test.target)

ValueError: ignored

In [123]:
word_label_freq = cond_prob * 40
word_label_freq

array([0.00051282, 0.00069064, 0.0009215 , 0.00115908, 0.0014147 ,
       0.00162669, 0.00187927, 0.00209584, 0.00232095, 0.00255824,
       0.00278363, 0.0030344 , 0.00328431, 0.00350877, 0.00374845,
       0.00395761, 0.0044544 , 0.00460526, 0.00547644, 0.00649926])

In [ ]:
num_word_in_classes = word_label_freq * 1

In [167]:
num_word_in_classes = 11314 * word_label_freq.flatten()
num_word_in_classes

array([   0.        ,   59.54736842,  119.09473684,  178.64210526,
        238.18947368,  297.73684211,  357.28421053,  416.83157895,
        476.37894737,  535.92631579,  595.47368421,  655.02105263,
        714.56842105,  774.11578947,  833.66315789,  893.21052632,
        952.75789474, 1012.30526316, 1071.85263158, 1131.4       ])

In [ ]:
def find_label(data):
    """
      Your code here
    """


In [ ]:
pred = []
for text in tqdm(test_data):
    pred.append(find_label(text))
metrics.accuracy_score(pred, newsgroups_test.target)