<a href="https://colab.research.google.com/github/TolleDennis/basic-ml-course/blob/master/Python_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
X = np.array([[1, 2], [3, 4]])
#v = np.array([1, 2]).reshape((2, 1))
v = np.array([1, 2])
np.dot(X, v) # no broadcasting
# X * v # broadcasting
# np.dot(v, X)
# X - X.mean(axis=0)

array([ 5, 11])

In [2]:
x = np.linspace(0, 10, 3)
x

array([ 0.,  5., 10.])

In [4]:
X = ["sherlock","Melissa","Anne"]
X.remove("sherlock")
X.extend(["Calcium",'Premature'])


In [5]:
X = ["sherlock","Melissa","Anne","Melissa","Andrew","Peter"]
X.count("Melissa")
X.index("Melissa")
X



['sherlock', 'Melissa', 'Anne', 'Melissa', 'Andrew', 'Peter']

In [6]:
'Melissa' in(X)

True

In [7]:
sorted(X)

['Andrew', 'Anne', 'Melissa', 'Melissa', 'Peter', 'sherlock']

In [8]:
x1 = "The meaning of life is "
x2 = "Survive"
x3 = x1 + str("at 78years")
x3

'The meaning of life is at 78years'

In [9]:
'playing {} and {}'.format('football','tennis')

'playing football and tennis'

In [10]:
serv = {"Andrew":1,
       "Alex:":3,
       "Benson":4,
       "Nicolas":8}
serv.update({"Maggie":23,"Elizabeth":12})
serv.pop("Maggie")

23

In [11]:
try:
    serv["Nicolas"]
    print(serv.get("Nicolas"))
    print(serv)
    
except KeyError as e:
    print("Error",e)

8
{'Andrew': 1, 'Alex:': 3, 'Benson': 4, 'Nicolas': 8, 'Elizabeth': 12}


In [12]:
serv.get('anne',"not found")

'not found'

In [13]:
languages = {'python', 'r', 'java'}
snakes = set(['cobra', 'viper', 'python']) 
x = languages & snakes
x

{'python'}

In [14]:
fruits = ['apple', 'banana', 'cherry']
for i in range(len(fruits) ):
    print(fruits[i].capitalize())

Apple
Banana
Cherry


In [15]:
print("fer")

fer


In [16]:
nums = [1, "sherry ", 3, 4, 5]
cubes = []
# for num in nums:
#     cubes.append(num*3)
# print(cubes)
cubes = [num*3 for num in nums]
cubes


[3, 'sherry sherry sherry ', 9, 12, 15]

In [17]:
stat = "Hey sally how are you today?"
stat.replace("sally", "kelly")

'Hey kelly how are you today?'

In [18]:
quote = """Computer technology is an emerging field. It is adamant that all stakeholders in computer come togethers
and benefit the world from the various activities that have emerged in certain field
"""
count = {word: 0 for word in set(quote.split())}
for word in quote.split():
    count[word] += 1
count

{'computer': 1,
 'various': 1,
 'certain': 1,
 'emerging': 1,
 'the': 2,
 'Computer': 1,
 'benefit': 1,
 'and': 1,
 'emerged': 1,
 'come': 1,
 'is': 2,
 'stakeholders': 1,
 'adamant': 1,
 'activities': 1,
 'togethers': 1,
 'all': 1,
 'field': 1,
 'in': 2,
 'world': 1,
 'have': 1,
 'an': 1,
 'field.': 1,
 'from': 1,
 'It': 1,
 'that': 2,
 'technology': 1}

In [19]:
dct = dict(a=[1, 2], b=[4, 5])
key = 'c'
try:
    dct[key]
except:
    print("Key %s is missing. Add it with empty value" % key)
dct['c'] = []
print(dct)

Key c is missing. Add it with empty value
{'a': [1, 2], 'b': [4, 5], 'c': []}


In [20]:

"Is it a {} its just a {}".format("cat","dog")

'Is it a cat its just a dog'

In [21]:
import regex as re
regex = re.compile("(sub-.+)_(ses-.+)_(mod-.+)")
strings = ["abcsub-033_ses-01_mod-mri", "defsub-044_ses-01_mod-mri", "ghisub-055_ses-02_mod-ctscan"]
print([regex.findall(s)[0] for s in strings])

[('sub-033', 'ses-01', 'mod-mri'), ('sub-044', 'ses-01', 'mod-mri'), ('sub-055', 'ses-02', 'mod-ctscan')]


In [22]:
import os
import tempfile

temp = tempfile.gettempdir()
cws = os.getcwd()
cws
temp

'/tmp'

In [23]:
# importing pandas as pd
import pandas as pd
  
# Creating the Series
sr = pd.Series([80, 25, 3, 80, 24, 25])
  
# Create the Index
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp']
  
# set the index
sr.index = index_
  
# Print the series
print(sr)

Coca Cola    80
Sprite       25
Coke          3
Fanta        80
Dew          24
ThumbsUp     25
dtype: int64


In [24]:
sr.factorize()

(array([0, 1, 2, 0, 3, 1]), Int64Index([80, 25, 3, 24], dtype='int64'))